### ISSUE TITLE
todo: all things currently outstanding

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/vault-server#402]
- [ ] make new landing page w/ up to date information
- [ ] fine-tune Llama2 for auto-cut 
- [ ] finish RR data upload and run it by kanadaj
- [ ] make browser extension for auto-cut
